#!/usr/bin/env bash

set -e
set -o pipefail

[[ -z "${KUBE_FZF_PATH}" ]] && source kube-fzf.sh || source $KUBE_FZF_PATH 
editcm() {
  local namespace_query configmap_query result namespace configmap_name

  _kube_fzf_handler "editdeploy" "$@"
  namespace_query=$(echo $args | awk -F '|' '{ print $1 }')
  configmap_query=$(echo $args | awk -F '|' '{ print $2 }')

  result=$(_kube_fzf_search_configmap "$namespace_query" "$configmap_query")
  IFS=$'|' read -r namespace configmap_name <<< "$result"

  _kube_fzf_echo "kubectl edit configmap $configmap_name --namespace='$namespace'"
  kubectl edit configmap $configmap_name --namespace=$namespace
}

editcm "$@"
