#!/usr/bin/env bash

set -e
set -o pipefail

[[ -z "${KUBE_FZF_PATH}" ]] && source kube-fzf.sh || source $KUBE_FZF_PATH

execpod() {
  local namespace_query pod_query cmd result namespace pod_name

  _kube_fzf_handler "execpod" "$@"
  IFS=$'|' read -r namespace_query pod_query cmd _unused _unused <<< "$args"

  result=$(_kube_fzf_search_pod "$namespace_query" "$pod_query")
  IFS=$'|' read -r namespace pod_name <<< "$result"

  local fzf_args=$(_kube_fzf_fzf_args "" "--select-1")
  local container_name=$(kubectl --insecure-skip-tls-verify get pod $pod_name --namespace=$namespace --output=jsonpath='{.spec.containers[*].name}' \
    | tr ' ' '\n' \
    | fzf $(echo $fzf_args))

  _kube_fzf_echo "kubectl exec --namespace='$namespace' $pod_name -c $container_name -it $cmd"
  kubectl --insecure-skip-tls-verify exec --namespace=$namespace $pod_name -c $container_name -it $cmd
}

execpod "$@"
