#!/usr/bin/env bash

source ./kube-fzf.sh

pfpod() {
  local namespace_query pod_query port result namespace pod_name open

  _kube_fzf_handler "pfpod" "$@" || return $(_kube_fzf_teardown 1)
  IFS=$'|' read -r namespace_query pod_query port open <<< "$args"

  result=$(_kube_fzf_search_pod "$namespace_query" "$pod_query")
  [ $? -ne 0 ] && echo "$result" && return $(_kube_fzf_teardown 1)
  IFS=$'|' read -r namespace pod_name <<< "$result"

  local fzf_args=$(_kube_fzf_fzf_args "" "--select-1")

  _kube_fzf_echo "kubectl port-forward --namespace='$namespace' $pod_name $port"
  $open && open_in_browser $port
  kubectl port-forward --namespace=$namespace $pod_name $port
  return $(_kube_fzf_teardown 0)
}

open_in_browser() {
  IFS=':' read -ra splitted_port <<< "$1"
  (sleep 3 && echo "Opening localhost:${splitted_port}" && open "http://localhost:${splitted_port}") &
}

pfpod "$@"
