#!/usr/bin/env bash

set -e
set -o pipefail

[[ -z "${KUBE_FZF_PATH}" ]] && source kube-fzf.sh || source $KUBE_FZF_PATH

tailjob() {
  local namespace_query job_query result namespace job_name

  _kube_fzf_handler "tailjob" "$@"
  namespace_query=$(echo $args | awk -F '|' '{ print $1 }')
  job_query=$(echo $args | awk -F '|' '{ print $2 }')

  result=$(_kube_fzf_search_job "$namespace_query" "$job_query")
  IFS=$'|' read -r namespace job_name <<< "$result"

  local fzf_args=$(_kube_fzf_fzf_args "" "--select-1")

  _kube_fzf_echo "kubectl logs --namespace='$namespace' --follow job/$job_name"
  kubectl logs --namespace=$namespace --follow job/$job_name
}

tailjob "$@"
