#!/usr/bin/env bash

source ./kube-fzf.sh

tailpod() {
  local namespace_query pod_query result namespace pod_name

  _kube_fzf_handler "tailpod" "$@" || return $(_kube_fzf_teardown 1)
  namespace_query=$(echo $args | awk -F '|' '{ print $1 }')
  pod_query=$(echo $args | awk -F '|' '{ print $2 }')

  result=$(_kube_fzf_search_pod "$namespace_query" "$pod_query")
  [ $? -ne 0 ] && echo "$result" && return $(_kube_fzf_teardown 1)
  IFS=$'|' read -r namespace pod_name <<< "$result"

  local fzf_args=$(_kube_fzf_fzf_args "" "--select-1")
  local container_name=$(kubectl get pod $pod_name --namespace=$namespace --output=jsonpath='{.spec.containers[*].name}' \
    | tr ' ' '\n' \
    | fzf $(echo $fzf_args))

  _kube_fzf_echo "kubectl logs --namespace='$namespace' --follow $pod_name -c $container_name"
  kubectl logs --namespace=$namespace --follow $pod_name -c $container_name
  return $(_kube_fzf_teardown 0)
}

tailpod "$@"
