#!/usr/bin/env bash

set -e
set -o pipefail

[[ -z "${KUBE_FZF_PATH}" ]] && source kube-fzf.sh || source $KUBE_FZF_PATH

tailpod() {
  local namespace_query pod_query result namespace pod_name

  _kube_fzf_handler "tailpod" "$@"
  namespace_query=$(echo $args | awk -F '|' '{ print $1 }')
  pod_query=$(echo $args | awk -F '|' '{ print $2 }')

  result=$(_kube_fzf_search_pod "$namespace_query" "$pod_query")
  IFS=$'|' read -r namespace pod_name <<< "$result"

  local fzf_args=$(_kube_fzf_fzf_args "" "--select-1")
  local container_name=$(kubectl --insecure-skip-tls-verify get pod $pod_name --namespace=$namespace --output=jsonpath='{.spec.containers[*].name}' \
    | tr ' ' '\n' \
    | fzf $(echo $fzf_args))

  _kube_fzf_echo "kubectl logs --namespace='$namespace' --follow $pod_name -c $container_name"
  kubectl --insecure-skip-tls-verify logs --namespace=$namespace --follow $pod_name -c $container_name
}

tailpod "$@"
